### ISSUE TITLE
Compile servus with avahi-client on ubuntu 16.04

### ISSUE THREAD

**Issue by cveezee** [HBPVIS/Servus#87]
I try to compile servus on a ubuntu 16.04 VM using following commands .
cmake ..
make

during cmake step following message gets logged
-- Servus [1.5.1-7-g059f391-dirty] without avahi-client

it seems that cmake is unable to find the avahi package.
Can you please let me know the step i need to take so that servus compiles with avahi-client

**Comment by hernando** [comment]
If you have the libavahi-client-dev package installed, it should work out of the box.
After confirming that the package is installed, run cmake like this: `cmake -DCOMMON_FIND_PACKAGE_QUIET=OFF ..`. That will make the configuration phase more verbose.

**Comment by cveezee** [comment]
@hernando Thanks for tip, installing the libavahi-client-dev package did the trick!

**Comment by hernando** [comment]
You're welcome
