### ISSUE TITLE
Win/OSX : ninja : "no work to do", vs2017 project nothing happens

### ISSUE THREAD

**Issue by benkuper** [HBPVIS/Servus#89]
Hello,
I'm trying to compile a static lib of Servus (or any type of lib for that matter..), but when I build it with cmake and then ninja (or vs 2017 x64), I don't find any generated lib file.

Do I miss a step ? Is there something missing in the readme to actually create a .lib (and header files as well) ?

What's strange is I remember having already done that last year, but I can't remember how and I'm stuck without knowing where to look...

Infos : 
 - I have DNSSD installed and detected (i had to add an extra cmake_module with FindDNSSD but it works)
 - I'm not using Qt5 or Boost

Thanks

**Comment by benkuper** [comment]
This actually happens if git is clone without ---recursive argument.
Would be great to add that to the build instructions in the readme !

**Comment by hernando** [comment]
We have updated the instructions following your suggestion
